#pragma once
#include "vertex_program.h"

struct ID3D10Blob;
namespace b2 {
enum class ShaderKind : unsigned {
    passthrough,clear_vertex,clear_pixel,display_vertex,display_pixel,gui_vertex,gui_pixel,
    combiner0,combiner1,combiner2,combiner3,combiner4,combiner5,combiner6,combiner7,combiner8,
    fixed0,fixed1,fixed2,fixed3,fixed4,fixed5,fixed6,vertex,launch,
    color,modulate2d,modulate_cube,modulate3d,flow_luma,flow_estimate,flow_cut,flow_interpolate,count
};
struct ShaderBinary {Bytes bytes;bool compiled=false;};
struct StaticVertex {VertexProgram program;bool launch=false;};
// The tool defines a compiler; the game links only the generated bytecode bank.
ShaderBinary shader_binary(ShaderKind,const VertexProgram* = nullptr);
std::span<const StaticVertex> static_vertex_shaders();
ID3D10Blob* shader_blob(ShaderKind);
std::string shader_source(ShaderKind);
const char* shader_profile(ShaderKind);
std::string compile_shaders(const std::filesystem::path& xbe,const std::filesystem::path& output,bool replace);
}
