# Preserve the pinned backend and its exact HLSL, replacing just its compiler
# calls with the same precompiled bytecode interface used by the game renderer.
file(READ "${imgui_SOURCE_DIR}/backends/imgui_impl_dx11.cpp" imgui_dx11)
set(gui_sources "#pragma once\n#include <string_view>\nnamespace b2 {\n")
foreach(stage IN ITEMS vertex pixel)
    string(FIND "${imgui_dx11}" "static const char* ${stage}Shader =" source_start)
    string(FIND "${imgui_dx11}" "ID3DBlob* ${stage}ShaderBlob;" source_end)
    if(source_start LESS 0 OR source_end LESS source_start)
        message(FATAL_ERROR "Pinned ImGui ${stage} shader source changed")
    endif()
    math(EXPR source_length "${source_end}-${source_start}")
    string(SUBSTRING "${imgui_dx11}" ${source_start} ${source_length} shader_source)
    string(REPLACE "static const char* ${stage}Shader" "inline constexpr std::string_view gui_${stage}_source" shader_declaration "${shader_source}")
    string(APPEND gui_sources "${shader_declaration}\n")
    string(REPLACE "${shader_source}" "" imgui_dx11 "${imgui_dx11}")
    if(stage STREQUAL "vertex")
        set(profile vs_4_0)
    else()
        set(profile ps_4_0)
    endif()
    set(compiler "if (FAILED(D3DCompile(${stage}Shader, strlen(${stage}Shader), nullptr, nullptr, nullptr, \"main\", \"${profile}\", 0, 0, &${stage}ShaderBlob, nullptr)))")
    string(FIND "${imgui_dx11}" "${compiler}" compiler_start)
    if(compiler_start LESS 0)
        message(FATAL_ERROR "Pinned ImGui shader compiler call changed")
    endif()
    string(REPLACE "${compiler}" "if ((${stage}ShaderBlob = b2::shader_blob(b2::ShaderKind::gui_${stage})) == nullptr)" imgui_dx11 "${imgui_dx11}")
endforeach()
string(APPEND gui_sources "}\n")
file(CONFIGURE OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/generated/gui_shaders.h" CONTENT "${gui_sources}" @ONLY)
string(REPLACE "#pragma comment(lib, \"d3dcompiler\")" "// Shader bytecode is supplied by the native build tool." imgui_dx11 "${imgui_dx11}")
file(CONFIGURE OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/generated/imgui_impl_dx11.cpp" CONTENT "#include \"shaders.h\"\n${imgui_dx11}" @ONLY)
